# Generated by Django 4.2.2 on 2023-07-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='질문제목')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('view_count', models.IntegerField(blank=True, default=0, verbose_name='조회수')),
                ('heart_count', models.IntegerField(blank=True, default=0, verbose_name='공감수')),
                ('all_voted_count', models.IntegerField(default=0, verbose_name='투표 참여 수')),
                ('category', models.CharField(choices=[('대인관계', '대인관계'), ('연애', '연애'), ('교육', '교육'), ('생활', '생활'), ('건강', '건강'), ('반려동물', '반려동물'), ('여행', '여행'), ('쇼핑', '쇼핑'), ('기타', '기타')], default='기타', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('content', models.CharField(max_length=100, verbose_name='내용')),
                ('vote', models.CharField(default='0%', max_length=10, verbose_name='투표율')),
                ('each_voted_count', models.IntegerField(default=0, verbose_name='선택지 투표 참여 수')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
