# Generated by Django 4.2.2 on 2023-07-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heart_count',
            field=models.IntegerField(null=True, verbose_name='공감수'),
        ),
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(null=True, verbose_name='조회수'),
        ),
    ]
