# Generated by Django 4.2.2 on 2023-07-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_heart_count_alter_post_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='selection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
