# Generated by Django 4.2.2 on 2023-07-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_heart_count_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('전체', '전체'), ('대인관계', '대인관계'), ('연애', '연애'), ('교육', '교육'), ('생활', '생활'), ('건강', '건강'), ('반려동물', '반려동물'), ('여행', '여행'), ('쇼핑', '쇼핑'), ('기타', '기타')], default='기타', max_length=20),
        ),
    ]
