# Generated by Django 4.2.2 on 2023-07-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_heart_count_alter_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', '대인관계'), ('2', '연애'), ('3', '교육'), ('4', '생활'), ('5', '건강'), ('6', '반려동물'), ('7', '여행'), ('8', '쇼핑'), ('9', '기타')], default='기타', max_length=20),
        ),
    ]
