# Generated by Django 4.2.2 on 2023-07-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='vote',
            field=models.CharField(default='50%', max_length=4, verbose_name='투표율'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
