# Generated by Django 4.2.2 on 2023-07-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_selection_vote_delete_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='vote',
            field=models.CharField(default='50%', max_length=10, verbose_name='투표율'),
        ),
    ]
