# Generated by Django 4.2.2 on 2023-07-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_selection_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='all_voted_count',
            field=models.IntegerField(default=0, verbose_name='투표 참여 수'),
        ),
        migrations.AddField(
            model_name='selection',
            name='each_voted_count',
            field=models.IntegerField(default=0, verbose_name='선택지 투표 참여 수'),
        ),
    ]
