# Generated by Django 4.2.2 on 2023-07-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_all_voted_count_selection_each_voted_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='vote',
            field=models.CharField(default='0%', max_length=10, verbose_name='투표율'),
        ),
    ]
